In [1]:
import numpy as np

In [2]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
A=np.random.randn(10)
A
### normal distribution of random numbers

array([ 0.94989073,  1.34848999, -1.93467807,  0.50988493, -0.39072005,
        1.15012492, -0.42942509,  1.87189622, -0.21760978, -0.06154226])

In [5]:
a1=np.random.randn(20)
a1

array([-1.19981665, -0.55015856, -1.50395268, -1.2020762 ,  0.16388653,
        0.29009774, -0.93224861,  0.2474872 , -0.94498579, -0.49054472,
       -0.00639275,  1.33345825, -0.86001219,  2.06619831,  0.58529715,
        0.26153286,  0.33138199,  0.7433688 ,  1.21844319, -0.80243801])

In [7]:
np.add(A+a1[0:10])

ValueError: invalid number of arguments

In [10]:
a2=a1[0:10]


In [11]:
a2

array([-1.19981665, -0.55015856, -1.50395268, -1.2020762 ,  0.16388653,
        0.29009774, -0.93224861,  0.2474872 , -0.94498579, -0.49054472])

In [13]:
a3=np.random.randn(20)
a3

array([-1.8100519 ,  0.55276348,  0.27357017, -1.2423518 ,  0.68711131,
       -0.03612164,  0.78874584, -1.74304563,  0.54599029,  0.29683406,
       -0.42402278,  0.47764963, -0.5098675 ,  1.45960496,  0.65691194,
        0.80564009,  0.28048837, -0.68343296, -0.64807874, -2.33033078])

In [14]:
np.add(A,a1[0:10])

array([-0.24992593,  0.79833143, -3.43863075, -0.69219127, -0.22683352,
        1.44022266, -1.3616737 ,  2.11938342, -1.16259557, -0.55208698])

In [15]:
np.maximum(a1,a3)

array([-1.19981665,  0.55276348,  0.27357017, -1.2020762 ,  0.68711131,
        0.29009774,  0.78874584,  0.2474872 ,  0.54599029,  0.29683406,
       -0.00639275,  1.33345825, -0.5098675 ,  2.06619831,  0.65691194,
        0.80564009,  0.33138199,  0.7433688 ,  1.21844319, -0.80243801])