In [1]:
import numpy as np

In [2]:
arr=np.arrange(0,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
slicedArr=arr[0:5]
slicedArr

array([0, 1, 2, 3, 4])

In [6]:
slicedArr[:]=99
slicedArr

array([99, 99, 99, 99, 99])

In [7]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [8]:
arr_copy=arr.copy()

In [9]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [10]:
arr_copy[:]=100
arr_copy
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [11]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
twod_arr=np.array(([23,4,67],[34,56,23],[34,67,89]),np.int32)
twod_arr

array([[23,  4, 67],
       [34, 56, 23],
       [34, 67, 89]])

In [19]:
twod_arr[0][2]

67

In [20]:
twod_arr[:2][1:]


array([[34, 56, 23]])

In [21]:
twod_arr[:2]

array([[23,  4, 67],
       [34, 56, 23]])

In [25]:
new2D=np.zeros((10,10),np.int32)
new2D

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
new2D.shape[1]

10

In [27]:
new2D.shape()

TypeError: 'tuple' object is not callable

In [29]:
for i in range(new2D.shape[1]):
    new2D[i]=i
new2D

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])