In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
array=np.array([1,2,3,4,5],dtype=int32)

NameError: name 'int32' is not defined

In [4]:
array=np.array([1,2,3,4,5],np.int32)


In [5]:
array

array([1, 2, 3, 4, 5])

In [6]:
array.append(np.array([1,2,3,4,5],np.int32))

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [7]:
array*array

array([ 1,  4,  9, 16, 25])

In [8]:
1/array

array([ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ])

In [9]:
array**4

array([  1,  16,  81, 256, 625], dtype=int32)

In [10]:
array

array([1, 2, 3, 4, 5])